# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'inaday_app_5859' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for inaday_app_5859

  pod 'Firebase/Core', '~> 6.3.0'
  pod 'Firebase/Auth', '~> 6.3.0'
  pod 'Firebase/Firestore', '~> 6.3.0'
  pod 'Firebase/Auth', '~> 6.3.0'
  pod 'Firebase/Messaging', '~> 6.3.0'

  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

end
